Problems/1003/ans_1003.py, Problems/1003/ans_1003_NonDynProg.py, Problems/1003/test_1003.py, Problems/1780/ans_1780.py, Problems/1780/test_1780.py, Problems/2447/ans_2447.py, Problems/2675/ans_2675.py, Problems/2675/test_2675.py
=> Daily commit 211109 - Problem 2447

10869.py, 10869_class.py, 2588.py
=> Problem 10869

Problems/2884/2884.py
=> BNR Solve problem #2884

Problems/1085/ans_1085_JHP.py, Problems/4153/ans_4153_JHP.py
=> Daily commit - Jaehyun Park

Problems/1010/ans_1010.py
계속 PR 하나에 쌓이면서 리뷰가 안되는고로,
브랜치 컨트롤으로 PR을 계속 날리는 방식으로 해보려 함.
=> Daily commit 211204 - Problem 1010

Problems/11650/ans_11650_JHP.py, Problems/2447/ans_2447_JHP.py, Problems/2581/ans_2581_JHP.py, Problems/2581/ans_2581_JHP_v2.py
소수 찾기 문제 인데, 반례를 찾는게 생각보다 어려웠던거 같습니다.
else로 반례 처리하는 부분을 고려하지 않으면, 호락호락하게 허락 안해주는 백준이네요....
=> Daily commit on 2021.12.02~12.06 - JHP

Problems/11729/ans_11729_JHP.py
재귀 문제를 풀면서 많이 공부가 되는거 같습니다.
다른 재귀 문제들도 좀 찾아서 많이 풀어봐야 할거 같아요ㅎㅎㅎ
(지환이형 말대로 재귀함수 의미를 이해하는게 중요한거 같아요)
=> Daily Commit on 2021.12.07

Problems/1149/ans_1149.py, Problems/1149/test_1149.py
오랜만에 난이도를 올리니 어렵당
도움이 될 것 같은 개념이 많아 주석 나름 열심히 달았으니 참고요
체크해뒀다가 나중에 풀어봐도 좋은 문제인듯.
=> Daily commit 211210 - Problem 1149

Problems/3053/ans_3053.py
알고리즘 같지도 않은 문제이지만 오늘 힘들었으니 그냥...
=> Daily commit 211209 - Problem 3053

Problems/1181/ans_1181_JHP.py, Problems/15649/ans_15649_JHP.py
=> Daily Commit on 2021.12.12

Problems/1018/ans_1018_JHP.py, Problems/1181/ans_1181_JHP.py, Problems/15649/ans_15649_JHP.py
이게 답은 다 나오는데, 왜 "틀렸습니다"가 뜨는지....잘 모르겠습니다.
아무리 봐도 잘 모르겠어서, Help를 쳐봅니다....
=> Daily commit 2021.12.14 - Problem 1018

Problems/2581/ans_2581_BNR.py
입출력은 나오는데 Run time error 떠서 확인 부탁드려요
=> Daily commit 2581 문제 Runtime error해결

Problems/3009/3009_ans_BNR.py
=> Daily commit BNR 3009

Problems/11444/ans_11444_JHK.py
=> Daily commit 211216 - Problem 11444

Problems/2580/ans_2580_JHK.py, Problems/2580/ans_2580_JHK_Fail.py, Problems/2580/test_2580_JHK.py
최적화 문제가 어렵구만...
비교를 위해 시간초과 나는것과 안나는것을 같이 올림.
=> Daily commit 211217 - Problem 2580

Problems/9663/ans_9663_JHK.py
억지로 억지로 pypy3로 성공하긴 했는데...
이런 접근이 코테에서 생각날지는 잘 모르겠당...
=> Daily commit 211215 - Problem 9663

Problems/14888/ans_14888_JHP.py
기존에 백트래킹 구조에서 For를 이용하여 값을 찾는 방식하고 조금 다르게 구현해보았습니다.
저도 매번 같은 방식으로 백트래킹을 풀고, 사고가 그쪽에만 박혀있어서 그런지 리뷰할 때도 동일한 방법 밖에 생각이 안나더라고요...
그래서 좀 찾아보고 공부하면서 풀어보니, 재귀 및 DFS를 좀더 나은 방법으로 구현하여 풀어질 수 있는 방법이라 생각됩니다.
=> (JHP) Daily Commit on 2022.01.08 : Problem 14888 

Problems/10828/ans_10828_JHP.py
Stack 부분을 하는데, 처음 문제라 그런지 쉬운 문제였네요...허허...
=> Daily commit on 2022.01.10 : Problem 10828 - Stack

Problems/9184/ans_9184.py
그냥 일반적인 memoization + 빡코딩 문제인데, 괜히 어렵게(점화식을 해석해보려함...) 접근했다가 시간 많이 씀.
=> Daily commit 211214 - Problem 9184

Problems/14888/ans_14888_JHK.py
사실상 Brute force가 backtracking 형태로 나타나는 문제
=> Daily commit 211219 - Problem 14888

Problems/1003/ans_1003_JHP.py
Dynamic Programming에 대한 목적과 효과는 이해를 했는데,
이걸 문제에 적용하여 푼다는게 굉장히 어렵네요...
DP 문제에서도 한참 헤맬거 같습니다...
=> Daily Commit on 2022.01.10 : Problem 1003, Dynamic Programming

Problems/1003/ans_1003_JHP(2).py, Problems/9184/ans_9184_JHP.py
memoization으로 따로 저장하는 부분을 만들어서 했는데...그래도 timeout이 발생하네요...
내일 좀더 보고 정식 PR 올리도록 하겠습니다.
=> Daily commit 20220114

Problems/1003/ans_1003_BNR.py
=> 220117_DailyCommit_1003_BNR

Problems/1149/ans_1149_JHP.py
RGB 거리에 N개의 집 색깔 칠하는 비용의 최솟값을 찾는 문제입니다.
(DYN Programming으로 풀라고 하였고, For를 이용한 Top-Down방식입니다.)
첫번째 집을 기준으로 합을 누적해가며 memo에 저장했고, 색상을 지속적으로 더해가는 방식으로 구현하였습니다.
=> Daily Commit 2022.01.23 : Problem 1149 (JHP)

Problems/1904/ans_1904_BNR.py
피보나치로 풀었는데..
이런 문제 풀 때 입력(N) = 0~5정도 까지 예상 결과 값 나열해 가면서 푸나요??
=> 220119_DailyCommit_1904_BNR

Problems/1149/ans_1149_BNR.py
이전 누적 값으로 계산해야 하는 걸.. 현재 최적 값으로 찾다가 헤맸네요.. 컨닝 좀 했어요..ㅋㅋ
=> 20220125_DailyCommit_1149_BNR

Problems/6603/ans_6603.py
=> Daily commit 211207 - Problem 6603

Problems/11053/ans_11053_BNR.py
DP로 풀 수 있는 LIS.
N^2의 시간복잡도를 가지게 때문에 이진탐색을 이용하는 방법도 있음.
다음엔 이진탐색을 구현해보는 걸로..
=> 220131_DailyCommit_11053_BNR

Problems/2579/ans_2579_JHP.py, Problems/2750/ans_2750_JHP.py, Problems/2750/ans_2750_JHP_bubble.py
for 말고 while로도 조건을 풀어봤는데, while이 좀더 runtime이 오래 걸리더라구요.
세미나도 들었지만, 안 풀어보니 또 잊어서 문제를 풀어보았습니다. bubble이나 insert나 방식은 동일은 매우 유사하네요.
=> Daily Commit on 2022.01.28 : Probelm 2750

Problems/11399/ans_11399_JHP.py
=> Daily Commit on 2022.02.05 : Problem 11399

Problems/11054/ans_11054_JHP.py
문제의 답은 맞고, 접근하는 방식이 틀리지 않아보이는데 Fail이 되는 이유를 정확히 모르겠네요.
바이토닉 수열을 찾으려고 하는데, ascending에서 가장 길이가 긴 위치를 찾은 다음에 해당 index부터 descending 되는 수열을 찾는거라고 생각했는데....답은 맞게 나오는데 반례가 뭘지 생각이 안나서 일단 PR Draft로 생성하여 업데이트 합니다.
--> 리뷰하면서 뭘 잘못했는지 깨달았습니다...정식 PR로 교체하겠습니다. (오름차순이 항상 내림차순보다 긴 경우에만 성립하는 방식이라서 방법을 바꿔 다시 commit하였습니다.)
=> Daily Commit on 2022.02.01 : Problem 11054

Problems/1932/ans_1932_BNR.py
=> 220126_Dailycommit_1932_BNR

Problems/2293/ans_2293_JHK.py
=> Daily commit 220201 - Problem 2293

Problems/2004/ans_2004_JHK.py
=> Daily commit 220213 - Problem 2004

Problems/1676/ans_1676_JHK.py
=> Daily commit 220211 - Problem 1676

Problems/11047/ans_11047_JHP.py, Problems/13305/ans_13305_JHP.py
=> Daily Commit on 2022.01.24 : Problem 11047

세미나/20220120_regex.PY
오늘 세미나 내용입니다.
지환, 재현 책임님은 다음주 화요일에 진행해요~
가능 시간 알려주세요
=> 220120_Regex_세미나

Problems/2805/ans_2805_BNR.py
이분탐색, function 구분, function overriding 시도
=> 220304_DailyCommit_2805_BNR

Problems/1992/ans_1992_JHP.py
윈터 복귀하고, 이제야 문제를 풀 수 있게 되었네요. 열심히 하겠숩니다ㅠ_ㅠ
=> Daily commit on 2022.03.14 : Problem 1992

Problems/2565/ans_2565_JHK.py
Longest increasing subsequence 갯수를 구하는 방법에 대해 이진탐색으로 구현
l으로 갯수만을 확인 할 수 있고, 내용은 실제 LIS와는 다름에 주의
https://seungkwan.tistory.com/8
=> Daily commit 211225 - Problem 2565

Problems/6064/ans_6064_JHK.py
=> Daily commit 220317 - Problem 6064

Problems/2164/ans_2164_BNR.py
=> 220322_DailyCommit_BNR

Problems/11444/ans_11444_JHP.py
Solve Fibonacci with using matrix multiply method
(그냥 풀면 계속 실패해서, Matrix 곱하기로 구하는 방법에 대해 좀 컷닝을 했네요....)
=> Daily Commit on 2022.04.02 : Problem 11444 

Problems/18258/ans_18258_YH.py
=> YYH - Problem 18258

Problems/10837/ans_10837_JHK.py
단순히 승부차기가 조기종료 되는 경우를 판별하는 것인데,
의외로 수식으로 표현하기가 머리아픔.
=> Daily commit 220303 - Problem 10837

Problems/10816/ans_10816_JHP.py
답은 정상적으로 나오는데 시간 초과가 발생되네요..해당 방법에 대한 수정을 해보고 PR 변경하도록 하겠습니다.
=> Daily Commit on 2022.04.17 : Problem 10816 Binary search - Card find #2

Problems/11866/ans_11866_JHP.py
요세푸스 문제인데, Pop을 두번해서 풀수 있는데 사실은 Circular Que를 이용하여 풀어보는게 더 좋을거 같아요.
=> Daily Commit on 2022.06.17 : Problem 11866 요세푸스 문제

Problems/1010/ans_1010_JHP.py
=> Daily commit on 2022.06.24 - Problem 1010 DP top-down

Problems/Programmers/67256/ans_67256_BNR.PY
=> 220606_DailyCommit_67256_BNR

Problems/1269/ans_1269_BNR.py
=> 220610_DailyCommit_1269_BNR

Problems/1463/ans_1463_BNR.py
=> 220621_DailyCommit_1463_BNR

Problems/12865/ans_12865_JHP.py
Knapsack (냅섹) 문제인데...점화식을 찾는게 어려워서 약간의 컷닝을 했습니다..
DP는 점화식 찾는게 항상 어려움이 있는거 같습니다..ㅠㅠ
=> Daily Commit on 2022.07.03 : Problem 12865 Knapsack Problem

Problems/1926/ans_1926_JHK.py
=> Daily commit 220628 - Problem 1926

Problems/20923/ans_20923_JHK.py
Python3로는 시간초과. 조건이 자잘하게 많아서 복잡..
=> Daily commit 220518 - Problem 20923

Problems/13702/ans_13702_JHK.py, Problems/15500/ans_15500_JHK.py
=> Daily commit 220423 - Problem 13702

Problems/14445/ans_14445_JHK.py
문제에서 빠져있는 조건: 케이크(?)를 나눠주고 남아도 됨.
=> Daily commit 220420 - Problem 14445

Problems/10799/ans_10799_JHK.py
stack 문젠데... stack으로 푸는 법이 생각이 안나네.
=> Daily commit 220416 - Problem 10799

Problems/11724/ans_11724_JHK.py
아팠던건 난데 왜 니네가 노나여
마음으로 함께 아팠던거라 생각하면 되나
=> Daily commit 220330 - Problem 11724

Problems/1735/ans_1735_JHK.py
=> Daily commit 220322 - Problem 1735

Problems/10800/ans_10800_JHK.py
개념은 잡아서 구현은 마쳤는데 시간초과를 해결 못하고 컨닝...
=> Daily commit 220316 - Problem 10800

Problems/4307/ans_4307_JHK.py
이해를 돕기위한 Hint : 두 개미가 부딪히기 전후 두 개미의 위치는, 두 개미가 부딪히지 않고 그냥 지나쳐갔을 때의 위치와 동일하다.
=> Daily commit 220302 - Problem 4307

Problems/12865/ans_12865_JHK.py, Problems/12865/test_12865_JHK.py
애매해서 슬쩍 컨닝을 해버렸는데 그 방법에 고착되버림... 그냥 공부한걸루..
=> Daily commit 220130 - Problem 12865

Problems/1520/ans_1520_JHK.py, Problems/1520/failed_1520_JHK.py, Problems/1520/test_1520_JHK.py
DP 푸는 사람들은 이 문제 리뷰 열심히 해보면 얻어가는게 있을 것 같음.
=> Daily commit 220128 - Problem 1520

Problems/11049/ans_11049_JHK.py
Python3로는 안풀리는 문제
pypy3로 풀어야 함.
=> Daily commit 220127 - Problem 11049

Problems/11066/failed_11066_JHK.py
=> Daily commit 220119 - Problem 11066 - Failed

Problems/2751/ans_2751_MergeSort_JHK.py, Problems/2751/ans_2751_QuickSort_JHK.py
Quick sort 연습용 - 이 문제는 Quick sort로는 풀리지 않음.
=> Daily commit 220120 - Problem 2751

Problems/1655/ans_1655_JHK.py
=> Daily commit 220111~220112 - Problem 1655

Problems/11279/ans_11279_arr_JHK.py
=> Daily commit 220110 - Problem 11279 - Array type

Problems/11279/ans_11279_JHK.py
=> Daily commit 220109 - Problem 11279
